version: '3.8'

services:
  chatbot:
    build: .
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - NEON_DB_USER=${NEON_DB_USER}
      - NEON_DB_PASSWORD=${NEON_DB_PASSWORD}
      - NEON_DB_HOST=${NEON_DB_HOST}
      - NEON_DB_NAME=${NEON_DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app