# This file contains your secrets/API keys
# Make sure this file is in .gitignore to avoid exposing sensitive information

# OpenAI API key
OPENAI_API_KEY = "sk-XTHKFxTEvOk7JTpKPCXfcUVV-zTsiMZO898_NgrsB6T3BlbkFJ-gLSe8OaT55NQHAMul5sXxzINLgdocAqV9sQQdESIA"

# Google Sheets connection
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/162fk4EmAOdHTkt0xDOcXgrefNwtWb5Ms1z-weLpsZ8Q/edit?usp=sharing"
type = "service_account"
project_id = "leanstartup-454415"
private_key_id = "8c88b1ad209f681bca77b02ce30ba4a040ad21c4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGK8CPso2VVHq6
5qd3TVtN5GMDq9mO3x1v3glddWAa830TWRNQGo1j2oZi01foYwZInW776n9bwDrG
/uzCNoQ7Li+ED9PeiiHtK0k3v22UtzaFhfr5CCmk/rlTG2aQjloY/gy3zGoYcT/S
akhnPPmHne0OY0aGlzP/T7ZqMGMn0No7uWFxkTn6V9JL9IqcpnWoRdZkjWDAZX6k
nKDDlDQ9X2fYadSgvsh8jz5tD+fN/9LxML3BNYxPinC7pa6YeMZ8Z8Xxiyg2oewH
Yly/19WltDII4f2iCKpIUW1Kj/REICnofQgC5qNhW/29bBJtjnx2UGe0lFCKDBR+
EkTWnyslAgMBAAECggEAQy8xHOaJZp+Z7kRlcSZqNnmf8e4wl2Xf+n2ZyjQRbYGw
HT+dMxKVbc13swh4rKHpzvOE3WYuYGJG6xEhHmTSJqgtVsXw6+kDwH7k10AQfBMz
Kkh2gjg4uiXbmafX+VkxhXiXwjZMn9XBL+p1en6rEEXDyRVyIw4fBEc3jj+yVhw5
K1YgKWBQlQ6+/YCEaRAYY3jFr7hCZg6mx/QohJyiE4Oc0cDX4BGgjNnfnyeEaxre
5mnYLalD/mtEvOCb0z6vwSQuRPLmHzyr7TTlc4rSAXgRG17d0cDSWW75CazUWAHG
rgncI9MKPybz4QuRLXQyjnUJzTRZxeCvZxkHJV2V3wKBgQDkfRr4fp38Sk6Y+c59
atqinxUc0OzsH60umbzVw8bDDIrUIADrrweMQm2/Qm7OjqN6ALh+dPzb3H5IQtgM
i6cPt0JTq5WBu3vEROe6tS64l37/KnyHdb4U2Z/GWOm3m/Y7RHLqUh6vCdKHH6Ey
Mmryo64bvDnnoXMIHDtCqq6JewKBgQDeCCMHAzmj87ZJ25aANhUQZqMYdD9XdNaP
QZ8QJpbfQ4i3893p5VFxgq9xBGvEvofcJFyWenWn3/11xs75FSkzMQ+5ChtiQhVT
XacVL89Xu70fPenXNBz0qIBj9CgrZh/dmhtubyH/XcAxMOY7br86c8LlI85uHSZc
klG2161r3wKBgHp4dFRtydDJI4frnjqrY7V2/6IKenO2JuWrkgQihA9YUbGR1ex+
TNVpZdn2id49pnJmoH1nx4Exlp609YkD8fACkpK2jdST4as6I9t38isPSQsMguM4
wUH7xCBU2DGKb1klP1NJ4RiBc07qLUTysVCNW22SXpdBep8GQt1hD1yxAoGBAL+a
7f9jPR7LdogOQ7ao9UyOBjlYOEFUxsQhsQ7S/mf1c8qrXNo31yzJxnUVh5rlgYDs
sCn7zATvO1+kDYDOThurPxJEMpV8ycKDk2ipNZlUnkSTvXTFuCc6MnIPhYrOOrmW
AA4xQXmKggzxUf3/+G6M76emWsKTzUMd0f6j6TipAoGAPRmqWAzvPclHwkb1PJ1x
4DsjgonJIsAWlxckJRNsMkmVbIWsNpr5A59aOlBi0+U5y0OHvhrlRVMgllV/Saeq
8qBoGFJ9z5GkId3lXBAyWkd10HLR007f5qjaujoImwIVnqM/AZmi8X0Wv4rhVBqe
J8JszbCVxpHJL9gs6z72Xzk=
-----END PRIVATE KEY-----"""
client_email = "python-leanstartup@leanstartup-454415.iam.gserviceaccount.com"
client_id = "102363510399161286894"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/python-leanstartup%40leanstartup-454415.iam.gserviceaccount.com"